# Generated by Django 5.2.12 on 2026-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('product_hash', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField()),
            ],
        ),
    ]
