# Generated by Django 5.2.12 on 2026-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_by_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_by_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
