# Generated by Django 5.2.12 on 2026-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(max_length=255)),
                ('number_id', models.CharField(max_length=255)),
                ('stx_private_key', models.CharField(max_length=255)),
            ],
        ),
    ]
