# Generated by Django 5.2.12 on 2026-03-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_usdc_amount', models.CharField(max_length=255)),
                ('target_stacks_address', models.CharField(max_length=255)),
                ('is_executed', models.BooleanField()),
                ('bridge_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
