# Generated by Django 5.2.12 on 2026-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
