# Generated by Django 5.2.12 on 2026-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='secretkey',
            new_name='secret_key',
        ),
        migrations.AddField(
            model_name='wallet',
            name='number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
